### ISSUE TITLE
Import error due to typo in include file name

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/cmsis-core-nxp-jn517x#2]
https://github.com/ARMmbed/cmsis-core-nxp-jn517x/blob/master/cmsis-core-nxp-jn517x/cmsis.h#L26

Here ```#include "JN517X.h"``` should be ```#include "JN517x.h"``` this does not affect mac or windows as their file names are case agnostic, but fails on Linux.

**Comment by bangaragirinxp** [comment]
Thanks for reporting this. The issue is fixed
